package com.abricot.hwmasivov2.hwmasivov2;

import java.util.LinkedHashSet;
import java.util.Map;
import java.util.HashMap;

import com.hp.uca.expert.alarm.Alarm;
import com.hp.uca.expert.scenario.Scenario;
import com.hp.uca.mediation.action.client.Action;
import com.hp.uca.mediation.action.jaxws.ActionResponseItem;
import com.hp.uca.expert.troubleticket.UttlAlarm;

/**
 * Clase utilitaria para crear Trouble Tickets (TT) en Service Manager,
 * similar a CorteFibraV10.
 */
public class ServiceManager {

    private ServiceManager() {
    }

    private static String extractSummary(String additionalText) {
        if (additionalText == null || additionalText.trim().isEmpty()) {
            return "";
        }
        int newlineIndex = additionalText.indexOf('\n');
        if (newlineIndex > 0) {
            return additionalText.substring(0, newlineIndex).trim();
        }
        return additionalText.trim();
    }

    /**
     * Crea un Trouble Ticket en Service Manager basado en una alarma (PA).
     *
     * @param theScenario el escenario actual
     * @param alarm       la alarma (Problem Alarm) para la cual se creará el TT
     * @return el identificador del TT creado o null si no se pudo crear
     */
    public static String createTroubleTicket(Scenario theScenario, Alarm alarm) {
        if (theScenario == null) {
            return null;
        }
        if (alarm == null) {
            theScenario.getLogger().error("No se puede crear TT: la alarma es requerida");
            return null;
        }

        int createTTEnabled = 1;
        try {
            if (alarm.getPassingFiltersParams() != null && alarm.getPassingFiltersParams().get("tags") != null) {
                Object enabledValue = ((java.util.Map<?, ?>) alarm.getPassingFiltersParams().get("tags")).get("CreateTTEnabled");
                if (enabledValue != null) {
                    createTTEnabled = Integer.parseInt(enabledValue.toString());
                }
            }
        } catch (Exception e) {
            theScenario.getLogger().warn("No se pudo leer CreateTTEnabled, se asume habilitado");
        }

        if (createTTEnabled != 1) {
            theScenario.getLogger().warn("CREACION DE TT DESHABILITADA (CreateTTEnabled={}) - No se creara ticket", createTTEnabled);
            return null;
        }

        theScenario.getLogger().info("═══════════════════════════════════════════════════════════════");
        theScenario.getLogger().info("INICIANDO CREACIÓN DE TROUBLE TICKET (PA NE Is Disconnected)");
        theScenario.getLogger().info("═══════════════════════════════════════════════════════════════");
        theScenario.getLogger().info("  Alarm ID             : {}", alarm.getIdentifier());
        theScenario.getLogger().info("  Source ID            : {}", alarm.getSourceIdentifier());
        theScenario.getLogger().info("  Event Time           : {}", alarm.getTimeInMilliseconds());

        try {
            String faultyEntity = alarm.getCustomFieldValue("realManagedEntity");
            if (faultyEntity == null || faultyEntity.trim().isEmpty()) {
                faultyEntity = alarm.getOriginatingManagedEntity();
            }

            String additionalText = null;
            try {
                additionalText = alarm.getStringField("additionalText");
            } catch (Exception e) {
                additionalText = alarm.getCustomFieldValue("additionalText");
            }

            String summary = extractSummary(additionalText);
            if (summary == null || summary.trim().isEmpty()) {
                summary = "TT creado automáticamente por UCA - PA NE Is Disconnected";
            }

            String description = additionalText;
            if (description == null || description.trim().isEmpty()) {
                description = String.format("Automatic Ticket creation generated by UCA:\n%s", alarm.getIdentifier());
            }

            theScenario.getLogger().info("  Faulty Entity        : {}", faultyEntity);
            theScenario.getLogger().info("  Summary              : {}", summary);
            theScenario.getLogger().info("  Description length   : {}", description != null ? description.length() : 0);

            UttlAlarm ualarm = new UttlAlarm("<s>" + alarm.getSourceIdentifier() + "</s><i>" + alarm.getIdentifier() + "</i>");
            Map<String, String> relatedAlarmsFields = new HashMap<>();
            relatedAlarmsFields.put("original_event_time", Long.toString(alarm.getTimeInMilliseconds()));
            if (alarm.getPerceivedSeverity() != null) {
                relatedAlarmsFields.put("perceived_severity", alarm.getPerceivedSeverity().value());
            }
            ualarm.setCustomFields(relatedAlarmsFields);

            LinkedHashSet<UttlAlarm> relatedAlarms = new LinkedHashSet<>();
            relatedAlarms.add(ualarm);

            theScenario.getLogger().info("  Related Alarms count : {}", relatedAlarms.size());

            Action actionTT = new Action("SM_CreateTT");
            actionTT.addCommand("userId", "UCA");
            actionTT.addCommand("userInput", "");
            actionTT.addCommand("faultyEntity", faultyEntity != null ? faultyEntity.trim() : "");
            actionTT.addUserData("relatedAlarms", relatedAlarms);
            actionTT.addCommand("description", description);
            actionTT.addCommand("summary", summary);

            theScenario.addAction(actionTT);
            actionTT.executeSync();

            theScenario.getLogger().info("─────────────────────────────────────────────────────────────");
            theScenario.getLogger().info("RESULTADO DE CREACIÓN DE TT:");
            theScenario.getLogger().info("  Action ID             : {}", actionTT.getActionId());
            Object actionStatusObj = actionTT.getActionStatus();
            if (actionStatusObj != null) {
                theScenario.getLogger().info("  Action Status         : {}", actionStatusObj.toString());
            } else {
                theScenario.getLogger().info("  Action Status         : (no disponible)");
            }
            String statusExplanation = actionTT.getActionStatusExplanation();
            if (statusExplanation != null && !statusExplanation.trim().isEmpty()) {
                theScenario.getLogger().info("  Status Explanation    : {}", statusExplanation);
            }

            String createdTTId = null;
            if (actionTT.getListActionResponseItem() != null && !actionTT.getListActionResponseItem().isEmpty()) {
                for (ActionResponseItem item : actionTT.getListActionResponseItem()) {
                    if (item != null && item.getOutput() != null && item.getOutput().getEntry() != null) {
                        for (ActionResponseItem.Output.Entry entry : item.getOutput().getEntry()) {
                            if (entry != null) {
                                String key = entry.getKey();
                                String value = entry.getValue();
                                if (key != null && key.equalsIgnoreCase("identifier")) {
                                    createdTTId = value;
                                    break;
                                }
                            }
                        }
                    }
                }
            }

            if (createdTTId != null && !createdTTId.trim().isEmpty()) {
                theScenario.getLogger().info("  TT ID creado          : {}", createdTTId);
            } else {
                theScenario.getLogger().warn("  No se pudo obtener el ID del TT creado de la respuesta");
            }

            theScenario.getLogger().info("═══════════════════════════════════════════════════════════════");
            return createdTTId;

        } catch (Exception e) {
            theScenario.getLogger().error("ERROR al crear TT: {}", e.getMessage(), e);
            theScenario.getLogger().error("Detalles: Alarm ID={}", alarm.getIdentifier());
            return null;
        }
    }
}
